services:
    _defaults:
        autoconfigure: true
        public: true

    Jdwiese\ContaoEntitiesCoreBundle\Repository\ArticleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\CalendarEventsRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\CalendarFeedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\CalendarRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\ContentRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\CrawlQueueRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\CronJobRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\FaqCategoryRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\FaqRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\FilesRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\FormFieldRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\FormRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\ImageSizeItemRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\ImageSizeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\LayoutRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\LogRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\MemberGroupRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\MemberRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\ModuleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\NewsArchiveRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\NewsFeedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\NewsRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\OptInRelatedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\OptInRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\PageRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\PreviewLinkRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\RememberMeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\SearchIndexRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\SearchRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\SearchTermRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\StyleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\StyleSheetRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\ThemeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TrustedDeviceRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\UndoRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\UserGroupRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\UserRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\VersionRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']
