services:
    _defaults:
        autoconfigure: true
        public: true

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlArticleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlCalendarEventsRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlCalendarFeedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlCalendarRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlContentRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlCrawlQueueRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlCronJobRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlFaqCategoryRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlFaqRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlFilesRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlFormFieldRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlFormRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlImageSizeItemRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlImageSizeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlLayoutRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlLogRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlMemberGroupRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlMemberRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlModuleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlNewsArchiveRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlNewsFeedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlNewsRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlOptInRelatedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlOptInRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlPageRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlPreviewLinkRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlRememberMeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlSearchIndexRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlSearchRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlSearchTermRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlStyleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlStyleSheetRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlThemeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlTrustedDeviceRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlUndoRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlUserGroupRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlUserRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Repository\TlVersionRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']
