services:
    _defaults:
        autoconfigure: true
        public: true

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlArticleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlContentRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlCrawlQueueRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlCronJobRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlFilesRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlFormFieldRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlFormRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlImageSizeItemRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlImageSizeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlLayoutRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlLogRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlMemberGroupRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlMemberRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlModuleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlOptInRelatedRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlOptInRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlPageRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlPreviewLinkRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlRememberMeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlSearchIndexRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlSearchRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlSearchTermRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlStyleRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlStyleSheetRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlThemeRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlTrustedDeviceRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlUndoRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlUserGroupRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlUserRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']

    Jdwiese\ContaoEntitiesCoreBundle\Entity\TlArticle\TlVersionRepository:
        tags: ['doctrine.repository_service']
        arguments: ['@doctrine']
