services:
    _defaults:
        autoconfigure: true

    jdwiese.contao_entities.repository.member_group:
        class: Jdwiese\ContaoEntitiesCoreBundle\Repository\MemberGroupRepository
        arguments:
            - '@doctrine'
